name: Pipeline Kubernetes
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Codigo projeto
      - run: echo "Obter código"
        uses: actions/checkout@v4
      - run: echo "Executar testes setup-dotnet"
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.x
      - name: execução de teste
        working-directory: ./02-review/src
        run: dotnet test

      - run: echo "Build da imagem Docker"
        name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} #nomes de variaveis na configuração do repositorio
          password: ${{ secrets.DOCKERHUB_TOKEN }} #

        name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: 
            waguinho/nome_imagem:v1 #v${{ github.run_number}}
            waguinho/nome_imagem:latest # também a versão latest
          context: ./02-review/src
          file: caminho do Dockerfile
          push: true

      - run: echo "Push da imagem Docker"
# Executar CI e CD em paralelo não esta correto sem o needs
  CD:
  needs: [CI] #Só executa depois que o CI passar
  runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
        uses: actions/checkout@v4

      - run: echo "Configurar o Kubeconfig"
        - uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.K8Sconfig }} #Colocar no repositorio por ser sensivel
            
      - run: echo "Executar o apply"
        - uses: Azure/k8s-deploy@v5
          with:
            manifests: 02-review/k8s/deployment.yaml #caminho do deployment.yaml
            images: waguinho/nome_imagem: #v${{ github.run_number}}