name: Pipeline Github Actions

on:
  push:
    branches: [develop]
  workflow_dispatch: # Dispara o workflow manual sem necessidade de commit

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter código do projeto
        uses: actions/checkout@v4

      - name: Executar testes setup-dotnet
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.x

      - name: Executar testes
        working-directory: ./02-review/src/Review-Filmes.Test.Unit
        run: dotnet test

      - name: Login no Docker Hub (Problema)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # nomes de variáveis na configuração do repositório
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem Docker
        uses: docker/build-push-action@v6
        with:
          tags: | # incrementa a cada commit v$ {{  }}
            waguinhocarvalho/review-jornada:v${{ github.run_number }}  
            waguinhocarvalho/review-jornada:latest
          context: ./02-review/src
          file: ./02-review/src/Review-Filmes.Web/Dockerfile
          push: true

  CD:
    needs: [CI] # Só executa depois que o CI passar
    runs-on: ubuntu-latest
    steps:
      - name: Obter código
        uses: actions/checkout@v4

      - name: Configurar o Kubeconfig
        run: echo "Configurar o Kubeconfig"

      - name: Executar o apply
        run: echo "Executar o apply"
