name: Pipeline Kubernetes
on:
  push:
    branches: [develop]
  workflow_dispatch: #Dispara o workflow manual sem necessidade de commit

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Codigo projeto
      - run: echo "Obter código"
        uses: actions/checkout@v4
      
      - run: echo "Build da imagem Docker"
        name: Login no Docker Hub
     
        name: Build and push
     
      - run: echo "Push da imagem Docker"
  CD:
  needs: [CI] #Só executa depois que o CI passar
  runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
        uses: actions/checkout@v4

      - run: echo "Configurar o Kubeconfig"
            
      - run: echo "Executar o apply"